import type { Metadata } from "next";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import RootLayout from "@/components/ui/Layout";

export const metadata: Metadata = {
  title: "Brayan Portfolio",
  description: "Generated by create next app",  
  verification:{
    google: process.env.GOOGLE_SEARCH_CONSOLE_VERIFICATION_KEY
  }
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return(
    <RootLayout>
      {children}
      <Analytics/>
    </RootLayout>
  )
}

