import type { Metadata } from "next";
import "./globals.css";
import RootLayout from "@/components/ui/Layout";

export const metadata: Metadata = {
  title: "Brayan Portfolio",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return(
    <RootLayout>{children}</RootLayout>
  )
}

